# Generated by Django 4.1.2 on 2023-04-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rbubbleuploader', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='kid',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
