# Generated by Django 4.1.2 on 2023-04-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rbubbleuploader', '0003_hotel_photo_kid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.AlterField(
            model_name='photo',
            name='kid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
